Mockup
SozonikOleg/html-css-registration-homework pull request #1
Opened 2019-02-12 11:31 UTC by SozonikOleg

Made a layout, but is partially added styles.

2019-02-12 12:33 UTC, RamanRudski requested changes
Не все требования к домашке выполнены.
![capture](https://user-images.githubusercontent.com/9767961/52635680-92f8b880-2edb-11e9-887f-a4aab1ac9dac.PNG)

2019-02-12 12:33 UTC, Erromanr commented on index.html
> +        <fieldset class="fieldset">
`fieldset ` используется внутри формы

2019-02-12 12:33 UTC, Erromanr commented on index.html
> +                    <input type="email" placeholder="Email" class="form-email">
Отсутствует атрибут `name`. Форма не отправит данные инпута.

2019-02-12 12:33 UTC, Erromanr commented on index.html
> +                    <input type="password" placeholder="Password" class="form-password">
Смотри комментарий выше.

2019-02-12 12:33 UTC, Erromanr commented on index.html
> +                    <button type="submit" formmethod="get" formaction="index.html" class="form-button">login</button>
неверный `formaction` должен быть указан url сервера на который отправляются данные (см. домашку).
`class="form-button"` названия класса не по БЭМ `button` это элемент, должно быть `form__button`(прочитать про БЭМ, исправить остальные классы).

2019-02-12 12:33 UTC, Erromanr commented on index.html
> +                    <input type="tel" placeholder="Mobile Phone" class="form-tel">
добавь атрибут `pattern` для валидации input

2019-02-12 14:46 UTC, SozonikOleg commented on index.html
> +        <fieldset class="fieldset">
Исправил.

2019-02-12 14:50 UTC, SozonikOleg commented on index.html
> +                    <input type="email" placeholder="Email" class="form-email">
Исправил

2019-02-12 14:50 UTC, SozonikOleg commented on index.html
> +                    <input type="password" placeholder="Password" class="form-password">
Исправил

2019-02-13 09:21 UTC, SozonikOleg commented on index.html
> +                    <button type="submit" formmethod="get" formaction="index.html" class="form-button">login</button>
Исправил

2019-02-13 09:43 UTC, SozonikOleg commented on index.html
> +                    <input type="tel" placeholder="Mobile Phone" class="form-tel">
Исправил

2019-02-13 10:22 UTC, RamanRudski approved these changes

2019-02-13 10:25 UTC, merged